### ISSUE TITLE
Exception thrown when loading SNES rom

### ISSUE THREAD

**Issue by Ashenfactory** [ircluzar/RTC#1]
The following load error was displayed when loading F-Zero for SNES:

> A core accepted the rom, but threw an exception while loading:
> 
> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
> Parameter name: index
> &nbsp;&nbsp;at
> System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
> at BizHawk.Common.HawkFile.BindArchiveMember(Int32 index) in
> C:\Users\philt\Downloads\Bizhawk-Release\BizHawk-Release\BizHawk.Common\HawkFile.cs:line331
> &nbsp;&nbsp;at
> BizHawk.Client.Common.RomLoader.HandleArchiveBinding(HawkFile file) in C:\Users\philt\Documents\PROJECTS\RTC\DevBizHawk_RTC\BizHawk.Client.Common\RomLoader.cs:line 200
> &nbsp;&nbsp;at BizHawk.Client.Common.RomLoader.LoadRom(String path, CoreComm nextComm, Boolean forceAccurateCore, Int32 recursiveCount) in C:\Users\philt\Documents\PROJECTS\RTC\DevBizHawk_RTC\BizHawk.Client.Common\RomLoader.cs:line 338

The error pops up about half the time when loading the ROM. Furthermore RTC will crash fairly consistently when reloading the SNES core when a ROM is loaded or when reloading a savestate for that ROM (blasting using the Glitch Harvester, etc.).

**Comment by ircluzar** [comment]
oh my god, i've been searching the origin of that error for days. The code never broke on my side but the executable kept killing itself without warning. Thank you so much for this stack trace !!

**Comment by Ashenfactory** [comment]
I've noticed that it isn't the same error every time. I havn't really been paying enough attention to notice any pattern to speak of. At any rate, this is the other load error I get:

> System.IO.IOException: The process cannot access the file because it is being used by another process.
> &nbsp;&nbsp;at System.IO.__Error.WinIOError(int32 errorCode, String maybeFullPath)
> &nbsp;&nbsp;at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
> &nbsp;&nbsp;at BizHawk.COmmon.InstanceDll..ctor(String dllPath) in C:\Users\philt\Downloads\BizHawk-Release\BizHawk-Release\BizHawk.Common\InstanceDll.cs:line 28
> &nbsp;&nbsp;at BizHawk.Emulation.Cores.Nintendo.SNES.LibsnesApi..ctor(String dllPath) in C:\Users\philt\Downloads\BizHawk-Release\BizHawk-Release\BizHawk.Emulation.Cores\Consoles\Nintendo\SNES\LibsnesApi.cs:line 66
> &nbsp;&nbsp;at BizHawk.Emulation.Cores.Nintendo.SNES.LibsnesCore..ctor(GameInfo game, Byte[] romData, Boolean deterministicEmulation, Byte[] xmlData, CoreComm comm, Object Settings, Object SyncSettings) in C:\Users\philt\Downloads\BizHawk-Release\BizHawk-Release\BizHawk.Emulation.Cores\Consoles\Nintendo\SNES\LibsnesCore.cs:line 57
> &nbsp;&nbsp;at BizHawk.Client.COmmon.RomLoader.LoadRom(String path, CoreComm nextComm, Boolean forceAccurateCore, Int32 recursiveCount) in C:Users\philt\Documents\PROJECTS\RTC\DevBizHawk_RTC\BizHawk.Client.Common\RomLoader.cs:line 732

**Comment by ircluzar** [comment]
i might end up having to re-implement the savestates in the glitch harvester. The code i used in there is based on an older version of bizhawk.

**Comment by Ashenfactory** [comment]
I've just checked again with 0.78 and I don't seem to be getting the "Index was out of range. Must be non-negative and less than the size of the collection", however, I am still getting the "The process cannot access the file because it is being used by another process"-message. As far as I can tell the stack trace is identical to the one I recieved in 0.77.

**Comment by ircluzar** [comment]
We have done a lot of progress on how the corruption is handled in 3.00
The new update may solve your issue. Please download it and try again.
